sonar.projectKey=Xmarcelo05_PROYECTO-F1
sonar.organization=xmarcelo05


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=PROYECTO-F1
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusiones de archivos que no requieren análisis de cobertura o estático
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/initdb/**,**/*.sql,**/*.md,**/*.txt

# Rutas de reportes de cobertura para Frontend (TypeScript) y Backend (Python)
sonar.javascript.lcov.reportPaths=PROYECTO-F1-Frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=PROYECTO-F1-Backend/coverage.xml