steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'PROYECTO-F1-Frontend'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://champions-magic-larry-tent.trycloudflare.com'
      - '--build-arg'
      - 'VITE_THESPORTSDB_API_KEY=123'
      - '--build-arg'
      - 'VITE_THESPORTSDB_BASE_URL=https://www.thesportsdb.com/api/v1/json'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-f1/frontend:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'PROYECTO-F1-Frontend'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-f1/frontend:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'proyecto-f1-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-f1/frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-f1/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
