name: 'Build and Deploy to Cloud Run'
on:
  push:
    branches:
      - 'master'   # <- cambia a 'main' si esa es tu rama principal

env:
  PROJECT_ID: 'project-37ca8556-4c5d-47bd-9fd'
  REGION: 'us-central1'
  SERVICE: 'pronosticos-f1-frontend'
  REPOSITORY: 'pronosticos-f1'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/807177859654/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'github-actions@project-37ca8556-4c5d-47bd-9fd.iam.gserviceaccount.com'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Check token identity'
        run: |
          curl -s -G --data-urlencode "access_token=${{ steps.auth.outputs.auth_token }}" https://oauth2.googleapis.com/tokeninfo

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" ./PROYECTO-F1-Frontend
          docker push "${DOCKER_TAG}"

      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: echo '${{ steps.deploy.outputs.url }}'
